database:
  server: "192.168.0.107,6201"
  database: "KB_Project_Dev"
  username: "python_user"
  password: "UxmIncaFJG8Q5F38T21R"

logging:
  level: "INFO"
  file: "./logs/app.log"

env:
  name: "dev"

sources:
  ms_kb_url: "https://sqlserverbuilds.blogspot.com/"
